import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
process.chdir(ROOT);

// ---------------------------------------------------------------------------
// Custom Transforms
// ---------------------------------------------------------------------------

// Source shadows are CSS strings ("0 1px 2px rgba(...)"), not DTCG composite
// objects. Pass through untouched so SD doesn't try to destructure them.
StyleDictionary.registerTransform({
  name: 'shadow/passthrough',
  type: 'value',
  filter: (token) => (token.$type ?? token.type) === 'shadow',
  transform: (token) => token.$value ?? token.value,
});

// Source easings are CSS keywords ("ease-in-out"), not DTCG cubicBezier
// arrays. Pass through untouched.
StyleDictionary.registerTransform({
  name: 'cubicBezier/passthrough',
  type: 'value',
  filter: (token) => (token.$type ?? token.type) === 'cubicBezier',
  transform: (token) => token.$value ?? token.value,
});

// CSS: convert px dimensions to rem (base 16).
StyleDictionary.registerTransform({
  name: 'vera/size/rem',
  type: 'value',
  filter: (token) => (token.$type ?? token.type) === 'dimension',
  transform: (token) => {
    const raw = String(token.$value ?? token.value);
    const val = parseFloat(raw);
    if (isNaN(val)) return raw;
    return `${val / 16}rem`;
  },
});

// CSS: convert ms durations to seconds.
StyleDictionary.registerTransform({
  name: 'vera/time/seconds',
  type: 'value',
  filter: (token) => (token.$type ?? token.type) === 'duration',
  transform: (token) => {
    const raw = String(token.$value ?? token.value);
    const val = parseFloat(raw);
    if (isNaN(val)) return raw;
    return `${val / 1000}s`;
  },
});

// TS: strip px suffix → numeric value.
StyleDictionary.registerTransform({
  name: 'size/pxToNumber',
  type: 'value',
  filter: (token) => {
    const type = token.$type ?? token.type;
    const raw = String(token.$value ?? token.value);
    return type === 'dimension' && raw.endsWith('px');
  },
  transform: (token) => parseFloat(String(token.$value ?? token.value)),
});

// TS: strip ms suffix → numeric value.
StyleDictionary.registerTransform({
  name: 'duration/msToNumber',
  type: 'value',
  filter: (token) => {
    const type = token.$type ?? token.type;
    const raw = String(token.$value ?? token.value);
    return type === 'duration' && raw.endsWith('ms');
  },
  transform: (token) => parseFloat(String(token.$value ?? token.value)),
});

// Name transform: full kebab-case with camelCase splitting and dot replacement.
// borderRadius → border-radius, paddingX → padding-x, 0.5 → 0-5
StyleDictionary.registerTransform({
  name: 'name/cti-kebab',
  type: 'name',
  transform: (token) =>
    token.path
      .map((seg) =>
        seg
          .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
          .replace(/\./g, '-')
          .toLowerCase(),
      )
      .join('-'),
});

// ---------------------------------------------------------------------------
// Custom Formats
// ---------------------------------------------------------------------------

// Nested TypeScript const with full type inference via `as const`.
StyleDictionary.registerFormat({
  name: 'typescript/nested-const',
  format: ({ dictionary }) => {
    const result = {};
    for (const token of dictionary.allTokens) {
      // Strip the top-level 'vera' wrapper from the path
      const path = token.path.slice(1);
      let current = result;
      for (let i = 0; i < path.length - 1; i++) {
        if (!current[path[i]]) current[path[i]] = {};
        current = current[path[i]];
      }
      current[path[path.length - 1]] = token.$value ?? token.value;
    }

    return [
      '// Auto-generated by Style Dictionary — do not edit manually',
      '',
      `export const tokens = ${JSON.stringify(result, null, 2)} as const;`,
      '',
      'export type Tokens = typeof tokens;',
      '',
    ].join('\n');
  },
});

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

const sd = new StyleDictionary({
  source: ['tokens/design-tokens.json'],
  usesDtcg: true,
  log: { verbosity: 'silent' },
  platforms: {
    css: {
      transforms: [
        'shadow/passthrough',
        'cubicBezier/passthrough',
        'name/cti-kebab',
        'vera/size/rem',
        'vera/time/seconds',
      ],
      buildPath: 'build/css/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
        },
      ],
    },
    ts: {
      transforms: [
        'shadow/passthrough',
        'cubicBezier/passthrough',
        'size/pxToNumber',
        'duration/msToNumber',
      ],
      buildPath: 'build/ts/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'typescript/nested-const',
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();

// ---------------------------------------------------------------------------
// Figma Output — DTCG JSON with the 'vera' wrapper stripped
// ---------------------------------------------------------------------------

const source = JSON.parse(readFileSync('tokens/design-tokens.json', 'utf-8'));
const { vera } = source;

mkdirSync('build/figma', { recursive: true });
writeFileSync('build/figma/vera.json', JSON.stringify(vera, null, 2) + '\n');

// ---------------------------------------------------------------------------
// Preview — re-embed current tokens into preview.html
// ---------------------------------------------------------------------------

const previewPath = 'preview.html';
if (existsSync(previewPath)) {
  let html = readFileSync(previewPath, 'utf-8');

  // Re-embed the full TOKENS object between markers. It's pretty-printed and
  // indented to sit inside the <script> block, so the file stays readable and
  // diffs stay meaningful. Markers (not a line-anchored regex) keep the replace
  // resilient to the object's leading indentation and spanning many lines.
  const indent = '      ';
  const tokensLiteral = JSON.stringify(source, null, 2)
    .split('\n')
    .map((line, i) => (i === 0 ? line : indent + line))
    .join('\n');
  html = html.replace(
    /(\/\/ @tokens:start\n)[\s\S]*?(\n[ \t]*\/\/ @tokens:end)/,
    (_, start, end) => `${start}${indent}const TOKENS = ${tokensLiteral};${end}`,
  );

  // Sync the preview's brand CSS variables to the primary ramp. These live in
  // CSS (outside TOKENS), so the swatch chrome would otherwise drift on retone.
  const primary = source.vera.color.primary;
  html = html
    .replace(/(--accent:\s*)#[0-9a-fA-F]{3,8}(;)/, `$1${primary['500'].$value}$2`)
    .replace(
      /(--accent-light:\s*)#[0-9a-fA-F]{3,8}(;)/,
      `$1${primary['50'].$value}$2`,
    );

  writeFileSync(previewPath, html);
}

console.log('\n\u2705 Built all token outputs:');
console.log('   build/css/tokens.css');
console.log('   build/ts/tokens.ts');
console.log('   build/figma/vera.json');
if (existsSync(previewPath)) console.log('   preview.html (tokens refreshed)');
